In [1]:
import torch
import torch.nn as nn


In [3]:
#define neural network
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        
        self.layer1 = nn.Linear(2, 16)  # input → hidden
        self.relu = nn.ReLU()
        self.layer2 = nn.Linear(16, 1)  # hidden → output
        
    def forward(self, x):
        x = self.layer1(x)
        x = self.relu(x)
        x = self.layer2(x)
        return x


In [5]:
#instantiate model
model = SimpleNN()
print(model)

SimpleNN(
  (layer1): Linear(in_features=2, out_features=16, bias=True)
  (relu): ReLU()
  (layer2): Linear(in_features=16, out_features=1, bias=True)
)


In [7]:
#dummy input
x = torch.tensor([[1.0, 2.0]])
output = model(x)

print("Output:", output)


Output: tensor([[0.0394]], grad_fn=<AddmmBackward0>)


In [18]:
#batch input
x_batch = torch.randn(5, 2)
print(x_batch)
outputs = model(x_batch)

print(outputs)


tensor([[-1.9113,  0.1206],
        [ 0.6821,  0.1086],
        [-0.3102, -0.6996],
        [-1.0558,  0.9221],
        [-0.2627, -1.0975]])
tensor([[-0.0946],
        [-0.0202],
        [-0.1135],
        [ 0.1423],
        [-0.2279]], grad_fn=<AddmmBackward0>)


In [11]:
#if we treat output as probability, let's use sigmoid for classification
sigmoid = torch.sigmoid(outputs)
print(sigmoid)


tensor([[0.4678],
        [0.5483],
        [0.4151],
        [0.4661],
        [0.5253]], grad_fn=<SigmoidBackward0>)


In [25]:
#weights are stored in
model.parameters()

<generator object Module.parameters at 0x12d2375f0>

# Neural Networks in PyTorch

## Objective
This notebook introduces the structure of a neural network using PyTorch’s `nn.Module` framework.

---

## Key Concepts

**nn.Module**  
Base class for all neural network models in PyTorch.

**Linear Layer (`nn.Linear`)**  
Applies affine transformation:

\[
y = Wx + b
\]

**Activation Function (ReLU)**  
Introduces nonlinearity required for modeling complex patterns.

---

## Key Insight
Neural networks are constructed by stacking layers and defining a forward computation describing how input data flows through the model.

Think of your NN as:
--Stack of differentiable math functions
Training =
--Adjust weights to minimize loss
(using gradients from autograd)
